apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../apps/project-a/base

nameSuffix: -dev

replicas:
  - name: api
    count: 1

images:
  - name: yourrepo/api
    newTag: dev

